{% raw %}---
- hosts: all

  tasks:

    - name: install deps
      apt:
        name={{ item }}
        state=present
      with_items:
        - git
        - ansible
      become: yes

    - name: clone batcave
      git:
        repo=https://github.com/xsteadfastx/batcave.git
        dest=~/batcave

    - name: run batcave
      command:
        ansible-playbook -i hosts base.yml -c local
        chdir=~/batcave{% endraw %}
